-- Words table
create table words (
  id uuid primary key default gen_random_uuid(),
  word text not null unique,
  month integer not null check (month between 1 and 12),
  year integer not null,
  deadline date not null,
  created_at timestamptz default now()
);

-- Papers table
create table papers (
  id uuid primary key default gen_random_uuid(),
  word_id uuid references words(id) on delete set null,
  type text not null default 'word' check (type in ('word', 'long-form')),
  title text,
  pdf_url text not null,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  -- Invisible hashtags: author-supplied metadata, never rendered; powers search only.
  tags text[] not null default '{}',
  submitted_at timestamptz default now()
);

-- Speeds up tag-based queries
create index papers_tags_idx on papers using gin (tags);

-- Comments table
create table comments (
  id uuid primary key default gen_random_uuid(),
  word_id uuid not null references words(id) on delete cascade,
  paper_id uuid references papers(id) on delete cascade,
  parent_comment_id uuid references comments(id) on delete cascade,
  body text not null,
  created_at timestamptz default now()
);

-- Messages table (contact form)
create table messages (
  id uuid primary key default gen_random_uuid(),
  body text not null,
  reply_email text,
  read boolean not null default false,
  created_at timestamptz default now()
);

-- RLS: enable on all tables
alter table words enable row level security;
alter table papers enable row level security;
alter table comments enable row level security;
alter table messages enable row level security;
-- messages: no public policies. All access is server-side via the service-role
-- admin client, which bypasses RLS.

-- Words: anyone can read
create policy "public read words"
  on words for select using (true);

-- Papers: anyone can read approved papers only
create policy "public read approved papers"
  on papers for select using (status = 'approved');

-- Comments: anyone can read
create policy "public read comments"
  on comments for select using (true);

-- Comments: anyone can insert
create policy "public insert comments"
  on comments for insert with check (true);

-- Storage bucket for PDFs
insert into storage.buckets (id, name, public)
  values ('papers', 'papers', false);

-- Storage: no public insert policy — uploads happen server-side via admin client
-- which bypasses RLS, so no policy needed here. Anon users cannot upload directly.

-- Storage: public cannot read objects directly — PDFs are served via signed URLs
-- generated by the API route, so the bucket stays fully private.

-- ============ Profiles (anonymous accounts) ============

-- profiles.id is the public author-page key — deliberately NOT the auth uid,
-- so nothing public ever shares an identifier with auth.users.
create table profiles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references auth.users(id) on delete cascade,
  email text not null,
  created_at timestamptz default now()
);

-- deadline_reminders is the master switch; the three window columns pick which
-- reminders it sends. Two weeks is off by default — it was added later, and
-- opting people in retroactively would mean sending mail nobody asked for.
create table notification_prefs (
  profile_id uuid primary key references profiles(id) on delete cascade,
  new_word boolean not null default true,
  deadline_reminders boolean not null default true,
  deadline_14d boolean not null default false,
  deadline_7d boolean not null default true,
  deadline_1d boolean not null default true,
  paper_comments boolean not null default true,
  comment_replies boolean not null default true,
  updated_at timestamptz default now()
);

-- Private link tables: which profile owns which paper/comment.
-- Kept out of papers/comments because those tables have public SELECT
-- policies — an author column there would be readable with the anon key.
create table paper_authors (
  paper_id uuid primary key references papers(id) on delete cascade,
  profile_id uuid not null references profiles(id) on delete cascade,
  -- Dormant: the public author page was removed; nothing reads or sets this
  -- to true today. Kept for a possible future opt-in sharing feature.
  public_visible boolean not null default false,
  created_at timestamptz default now()
);
create index paper_authors_profile_idx on paper_authors(profile_id);

create table comment_authors (
  comment_id uuid primary key references comments(id) on delete cascade,
  profile_id uuid not null references profiles(id) on delete cascade
);
create index comment_authors_profile_idx on comment_authors(profile_id);

-- Sent-log for notification dedupe (claim-then-send).
-- kind: 'new_word' | 'deadline_7d' | 'deadline_1d' (ref_id = word_id)
--       'paper_comment' | 'comment_reply'          (ref_id = comment_id)
create table notification_log (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references profiles(id) on delete cascade,
  kind text not null,
  ref_id uuid,
  sent_at timestamptz default now(),
  unique (profile_id, kind, ref_id)
);

-- RLS enabled with ZERO policies: these tables are invisible to the anon key.
-- All access goes through API routes using the service-role client.
alter table profiles enable row level security;
alter table notification_prefs enable row level security;
alter table paper_authors enable row level security;
alter table comment_authors enable row level security;
alter table notification_log enable row level security;

-- ============ Rate limiting ============

-- Shared counter store for the upload and admin-login limiters. Defined in
-- full — table plus the atomic rate_limit_hit() / prune_rate_limits()
-- functions — in supabase/migrations/0003_rate_limits.sql. Run that migration
-- rather than copying from here; this section exists so a from-scratch setup
-- knows the table belongs to the schema.
--
-- create table rate_limits (
--   key text primary key,
--   count integer not null default 0,
--   window_start timestamptz not null default now()
-- );
-- alter table rate_limits enable row level security;
