-- Words table
create table words (
  id uuid primary key default gen_random_uuid(),
  word text not null unique,
  month integer not null check (month between 1 and 12),
  year integer not null,
  deadline date not null,
  created_at timestamptz default now()
);

-- Papers table
create table papers (
  id uuid primary key default gen_random_uuid(),
  word_id uuid references words(id) on delete set null,
  type text not null default 'word' check (type in ('word', 'long-form')),
  title text,
  pdf_url text not null,
  email text not null,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  submitted_at timestamptz default now()
);

-- Unique: one submission per email per word
create unique index one_per_email_per_word
  on papers (email, word_id)
  where word_id is not null and type = 'word';

-- Comments table
create table comments (
  id uuid primary key default gen_random_uuid(),
  word_id uuid not null references words(id) on delete cascade,
  paper_id uuid references papers(id) on delete cascade,
  parent_comment_id uuid references comments(id) on delete cascade,
  body text not null,
  created_at timestamptz default now()
);

-- RLS: enable on all tables
alter table words enable row level security;
alter table papers enable row level security;
alter table comments enable row level security;

-- Words: anyone can read
create policy "public read words"
  on words for select using (true);

-- Papers: anyone can read approved papers only
create policy "public read approved papers"
  on papers for select using (status = 'approved');

-- Comments: anyone can read
create policy "public read comments"
  on comments for select using (true);

-- Comments: anyone can insert
create policy "public insert comments"
  on comments for insert with check (true);

-- Storage bucket for PDFs
insert into storage.buckets (id, name, public)
  values ('papers', 'papers', false);

-- Storage: no public insert policy — uploads happen server-side via admin client
-- which bypasses RLS, so no policy needed here. Anon users cannot upload directly.

-- Storage: public cannot read objects directly — PDFs are served via signed URLs
-- generated by the API route, so the bucket stays fully private.
